baseURL = "https://github.com/MisterCodo/recipes"
languageCode = "en-us"
title = "Recettes"
theme = "cookbook"
sectionPagesMenu = "main"

[params.front]
defaultAuthor = ""
defaultImage = "images/defaultImage.jpg"
defaultImageHeight = 512
defaultImageWidth = 512

# If you have a logo image, add it here, else just text (as an image) will be added
# The default height/width are the recommended bulma size (112W X 28H), best to get your logo as close as possible to that
# The site will SCALE your image, but will not force a stretch, so you may need to stretch it in external tool before using.
[params.logo]
fileName = "images/logo.webp"
height = 50
width = 200

[menu]
[[menu.main]]
name = "Maison"
pre = "fas fa-home"
url = "/"
weight = 1
[[menu.main]]
name = "Cat√©gories"
pre = "fas fa-tags"
url = "/tags/"
weight = 2

# Print output just creates a special route for a print view
[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "PRINT"]

# The settings for the print format
[outputFormats]
[outputFormats.printFormat]
name = "print"
mediaType = "text/html"
baseName = "print"
isPlainText = false
rel = "print"
isHTML = true
noUgly = true
permalinkable = true
path = "print"
